const base = "/jsx";
const baseURL = "http://43.205.148.119:7000/api/v1/";
//const baseURL = "https://web.nnlone.com/api/v1/";
//const baseURL = "http://localhost:7000/api/v1/";
const baseRoute = "/";
const imageURL = "https://images.com";

export const Paths = {
  Home: base,
  LearningPath: baseRoute + "Learning",
  EndpointsURL: {
    PostTopForm: baseURL + "form",
    HomeNNLCourses: baseURL + "all/courses",
    HomeWhyChoose: baseURL + "all/why/choose",
    HomeMasterMind: baseURL + "all/mastermind",
    VideoSnippts: baseURL + "all/video/snippts",
    HomeNextians: baseURL + "all/nextians",
    HomeCommonTab: baseURL + "all/common/tab",
    HomeShareFeedback: baseURL + "feedback",
    HomeFAQ: baseURL + "all/faq",
    OffersForm: baseURL + "query/form",
    NNLExams: baseURL + "all/exams",
    AIIMSNORCETBanner: baseURL + "all/norcet/banner",
    CHOBanner: baseURL + "all/cho/banner",
    NNLExamsBanner: baseURL + "all/exams/banner",
    MastermindBanner: baseURL + "all/mastermind/banner",
    HomeBanner: baseURL + "all/home/banner",
    BlogsBanner: baseURL + "all/blogs/banner",
    NextiansBanner: baseURL + "all/nextians/banner",
    AboutUsBanner: baseURL + "all/about-us/banner",
    CourseBanner: baseURL + "all/courses/banner",
    StoriesBanner: baseURL + "all/stories/banner",
    WhyChooseUs: baseURL + "all/why/choose",
    SuccessStories: baseURL + "all/success/stories",
    SinglePlanVideos: baseURL + "all/new/courses/",
    SinglePlanDetails: baseURL + "all/course/plan",
    SinglePlanSilentFeatures: baseURL + "all/course/plan",
    SinglePlanReferCourses: baseURL + "all/refer/course",
    PlanZeroBanner: baseURL + "all/plan-zero/banner",
    PlanABanner: baseURL + "all/plan-a/banner",
    PlanBBanner: baseURL + "all/plan-b/banner",
    PlanCPlusBanner: baseURL + "all/plan-c/banner",
    PlanMscBanner: baseURL + "all/plan-msc/banner",
    PlanUGBanner: baseURL + "all/plan-ug/banner",
    PlanTHBanner: baseURL + "all/plan-th/banner",
    PlanNNLBanner: baseURL + "all/plan-nnl-vsl/banner",
    OffersBanner: baseURL + "all/offers/banner",
    OfferOfMonths: baseURL + "all/months/offers/",
    NewsRoom: baseURL + "all/newsroom/",
    NewsRoomBanner: baseURL + "all/newsroom/banner/",
    CPlusVideos: baseURL + "all/c-plus/video",
    CPlusStats: baseURL + "all/c-plus/stats",
    CPlusSalient: baseURL + "all/c-plus/salient",
    CPlusKnowMorePrices: baseURL + "all/c-plus/price",
    CPlusReferCourses: baseURL + "all/c-plus/refer",
    PlanUGVideos: baseURL + "all/ug/video",
    PlanUGStats: baseURL + "all/ug/stats",
    PlanUGSalient: baseURL + "all/ug/salient",
    PlanUGKnowMorePrices: baseURL + "all/ug/price",
    PlanMLBLiteBanner: baseURL + "all/plan-mlb-lite/banner",
    MLBLiteVideos: baseURL + "all/mlb-lite/video",
    MLBLiteStats: baseURL + "all/mlb-lite/stats",
    MLBLiteSalient: baseURL + "all/mlb-lite/salient",
    MLBLiteKnowMorePrice: baseURL + "all/mlb-lite/price",
    PlanMLBPROBanner: baseURL + "all/plan-mlb-pro/banner",
    MLBPROVideos: baseURL + "all/mlb-pro/video",
    MLBPROKnowMorePrice: baseURL + "all/mlb-pro/price",
    MLBPROStats: baseURL + "all/mlb-pro/stats",
    MLBPROSalient: baseURL + "all/mlb-pro/salient",
    PlanZeroVideo: baseURL + "all/zero/video",
    PlanZeroOffersPrice: baseURL + "all/plan/zero/price",
    PlanZeroSalient: baseURL + "all/plan/zero/salient",
    PlanZeroStats: baseURL + "all/plan/zero/stats",
    PlanMscVideo: baseURL + "all/msc/video",
    PlanMscOffersPrice: baseURL + "all/msc/price",
    PlanMscSalient: baseURL + "all/msc/salient",
    PlanMscStats: baseURL + "all/msc/stats",
  },

  imagePathURL: {
    URL: imageURL,
  },
};
